include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    avoid_dynamic_calls: false
    unnecessary_await_in_return: false
    lines_longer_than_80_chars: false
    unnecessary_to_list_in_spreads: false
    cast_nullable_to_non_nullable: false
    parameter_assignments: false
    use_build_context_synchronously: false
    non_constant_identifier_names: false

analyzer:
  plugins:
    - very_good_analysis
  errors:
    deprecated_member_use_from_same_package: ignore
  exclude:
    - lib/firebase_options.dart
    
dart_code_metrics:
  metrics-exlude:
    - test/**
    - lib/src/generated/**
    - lib/src/generated_plugin_registrant.dart
