name: wishiz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_database: ^10.2.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.3.10
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  intl: any
  json_annotation: ^4.8.1
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  receive_sharing_intent: ^1.4.5
  riverpod_annotation: ^2.1.4
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.13

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.1
  very_good_analysis: ^5.1.0

flutter_native_splash:
  color: "#c792eb"
  image: assets/img/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/round_icon.png"
  macos:
    generate: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/img/
    - assets/google_fonts/
